# This script takes the CSV file exported from BOS with the survey data

# Specify which file to open
infile <- "data/results-for-investigating-2016-08-27-1923-coded.csv"

# And where to store results
plotspath <- "plots"
tablespath <- "tables"


# Read survey data
survey <- read.csv(infile)

# Replace the long names of the columns by just the question codes
# E.g. "X1..My.question" is replaced by "X1" in the column names.
names(survey) <- gsub("^(.*?)\\.\\.(.*)", "\\1", colnames(survey))
# TO DO: salvage the full question names somewhat
# so as not to depend on survey keys for question names.

# Delete email information if still present
survey$Q16 <- NULL

# Output total number of responses
survey_tot <- nrow(survey)
print(paste('Total number of responses:', survey_tot))


# Convert key generated by BOS to key for analysis

# For Q3 and Q8, BOS coded "Don't know/NA" as "4", convert to "NA"
survey$Q3_1_a[survey$Q3_1_a==4] <- NA
survey$Q3_2_a[survey$Q3_2_a==4] <- NA
survey$Q3_3_a[survey$Q3_3_a==4] <- NA
survey$Q3_4_a[survey$Q3_4_a==4] <- NA
survey$Q3_5_a[survey$Q3_5_a==4] <- NA
survey$Q3_6_a[survey$Q3_6_a==4] <- NA
survey$Q3_7_a[survey$Q3_7_a==4] <- NA
survey$Q3_8_a[survey$Q3_8_a==4] <- NA
survey$Q3_9_a[survey$Q3_9_a==4] <- NA
survey$Q3_10_a[survey$Q3_10_a==4] <- NA
survey$Q8_1_a[survey$Q8_1_a==4] <- NA
survey$Q8_2_a[survey$Q8_2_a==4] <- NA
survey$Q8_3_a[survey$Q8_3_a==4] <- NA
survey$Q8_4_a[survey$Q8_4_a==4] <- NA
survey$Q8_5_a[survey$Q8_5_a==4] <- NA
survey$Q8_6_a[survey$Q8_6_a==4] <- NA
survey$Q8_7_a[survey$Q8_7_a==4] <- NA
survey$Q8_8_a[survey$Q8_8_a==4] <- NA
survey$Q8_9_a[survey$Q8_9_a==4] <- NA
survey$Q8_10_a[survey$Q8_10_a==4] <- NA

# For Q9 and Q10, BOS coded "Not sure / don't know" as "3", convert to "NA"
survey$Q9[survey$Q9==3] <- NA
survey$Q10[survey$Q10==3] <- NA

# For Q11, Q12, Q13, Q14, BOS coded "N/A" as "6", convert to "NA"
survey$Q11_1_a[survey$Q11_1_a==6] <- NA
survey$Q11_2_a[survey$Q11_2_a==6] <- NA
survey$Q11_3_a[survey$Q11_3_a==6] <- NA
survey$Q11_4_a[survey$Q11_4_a==6] <- NA
survey$Q11_5_a[survey$Q11_5_a==6] <- NA
survey$Q11_6_a[survey$Q11_6_a==6] <- NA
survey$Q12_1_a[survey$Q12_1_a==6] <- NA
survey$Q12_2_a[survey$Q12_2_a==6] <- NA
survey$Q12_3_a[survey$Q12_3_a==6] <- NA
survey$Q12_4_a[survey$Q12_4_a==6] <- NA
survey$Q12_5_a[survey$Q12_5_a==6] <- NA
survey$Q12_6_a[survey$Q12_6_a==6] <- NA
survey$Q12_7_a[survey$Q12_7_a==6] <- NA
survey$Q12_8_a[survey$Q12_8_a==6] <- NA
survey$Q12_9_a[survey$Q12_9_a==6] <- NA
survey$Q12_10_a[survey$Q12_10_a==6] <- NA
survey$Q12_11_a[survey$Q12_11_a==6] <- NA
survey$Q13_1_a[survey$Q13_1_a==6] <- NA
survey$Q13_2_a[survey$Q13_2_a==6] <- NA
survey$Q14_1_a[survey$Q14_1_a==6] <- NA
survey$Q14_2_a[survey$Q14_2_a==6] <- NA
survey$Q14_3_a[survey$Q14_3_a==6] <- NA

print('Data prep done.')